services:
  webapp:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
